AspNetMvcAds.Web.Mvc/Controllers/CategoryController.cs
using AspNetMvcAds.Business;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;

        public CategoryController(ICategoryService categoryService, IProductService productService)
        {
            _categoryService = categoryService;
            _productService = productService;
        }

        // category/index/cid
        public IActionResult Index(int cid)
        {
            var list = _productService.GetAllAdvert(cid);
            ViewBag.SubCategories = _categoryService.GetAllSubCategories();
            return View(list);
        }

        public IActionResult AddListing()
        {
            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/ViewComponents/NavbarViewComponent.cs
using AspNetMvcAds.Business;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.ViewComponents
{
    public class NavbarViewComponent : ViewComponent 
    {
        private readonly ICategoryService categoryService;

        public NavbarViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.MainCategories = categoryService.GetAllMainCategories();

            ViewBag.SubCategories = categoryService.GetAllSubCategories();

            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/Views/Shared/_CallToAction.cshtml
<section class="call-to-action overly bg-3 section-sm">
	<!-- Container Start -->
	<div class="container">
		<div class="row justify-content-md-center text-center">
			<div class="col-md-8">
				<div class="content-holder">
					<h2>
						Start today to get more exposure and
						grow your business
					</h2>
					<ul class="list-inline mt-30">
						<li class="list-inline-item"><a class="btn btn-main" asp-controller="Category" asp-action="Addlisting">Add Listing</a></li>
						<li class="list-inline-item"><a class="btn btn-secondary" asp-controller="Category" asp-action="Index">Browser Listing</a></li>
					</ul>

				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->

</section>

AspNetMvcAds.Web.Mvc/Views/Shared/_Footer.cshtml
<footer class="footer section section-sm">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-7 offset-md-1 offset-lg-0">
				<!-- About -->
				<div class="block about">
					<!-- footer logo -->
					<img src="~/images/logo-footer.png" alt="">
					<!-- description -->
					<p class="alt-color">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
						incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
						laboris nisi ut aliquip ex ea commodo consequat.
					</p>
				</div>
			</div>
			<!-- Link list -->
			<div class="col-lg-2 offset-lg-1 col-md-3">
				<div class="block">
					<h4>Site Pages</h4>
					<ul>
						<li><a href="#">Boston</a></li>
						<li><a href="#">How It works</a></li>
						<li><a href="#">Deals & Coupons</a></li>
						<li><a href="#">Articls & Tips</a></li>
						<li><a href="terms-condition.html">Terms & Conditions</a></li>
					</ul>
				</div>
			</div>
			<!-- Link list -->
			<div class="col-lg-2 col-md-3 offset-md-1 offset-lg-0">
				<div class="block">
					<h4>Admin Pages</h4>
					<ul>
						<li><a href="category.html">Category</a></li>
						<li><a href="single.html">Single Page</a></li>
						<li><a href="store.html">Store Single</a></li>
						<li>
							<a href="single-blog.html">Single Post</a>
						</li>
						<li><a href="blog.html">Blog</a></li>



					</ul>
				</div>
			</div>
			<!-- Promotion -->
			<div class="col-lg-4 col-md-7">
				<!-- App promotion -->
				<div class="block-2 app-promotion">
					<div class="mobile d-flex">
						<a href="">
							<!-- Icon -->
							<img src="~/images/footer/phone-icon.png" alt="mobile-icon">
						</a>
						<p>Get the Dealsy Mobile App and Save more</p>
					</div>
					<div class="download-btn d-flex my-3">
						<a href="#"><img src="~/images/apps/google-play-store.png" class="img-fluid" alt=""></a>
						<a href="#" class=" ml-3"><img src="images/apps/apple-app-store.png" class="img-fluid" alt=""></a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</footer>
<!-- Footer Bottom -->
<footer class="footer-bottom">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-12">
				<!-- Copyright -->
				<div class="copyright">
					<p>
						Copyright © <script>
							var CurrentYear = new Date().getFullYear()
							document.write(CurrentYear)
						</script>. All Rights Reserved, theme by <a class="text-primary" href="https://themefisher.com" target="_blank">themefisher.com</a>
					</p>
				</div>
			</div>
			<div class="col-sm-6 col-12">
				<!-- Social Icons -->
				<ul class="social-media-icons text-right">
					<li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-vimeo" href=""></a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- Container End -->
	<!-- To Top -->
	<div class="top-to">
		<a id="top" class="" href="#"><i class="fa fa-angle-up"></i></a>
	</div>
</footer>

AspNetMvcAds.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- SITE TITTLE -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Classimax</title>

	<!-- FAVICON -->
	<link href="~/img/favicon.png" rel="shortcut icon">
	<!-- PLUGINS CSS STYLE -->
	<!-- <link href="plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet"> -->
	<!-- Bootstrap -->
	<link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap-slider.css">
	<!-- Font Awesome -->
	<link href="~/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<!-- Owl Carousel -->
	<link href="~/plugins/slick-carousel/slick/slick.css" rel="stylesheet">
	<link href="~/plugins/slick-carousel/slick/slick-theme.css" rel="stylesheet">
	<!-- Fancy Box -->
	<link href="~/plugins/fancybox/jquery.fancybox.pack.css" rel="stylesheet">
	<link href="~/plugins/jquery-nice-select/css/nice-select.css" rel="stylesheet">
	<!-- CUSTOM CSS -->
	<link href="~/css/style.css" rel="stylesheet">

	


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body class="body-wrapper">
	

	@await Component.InvokeAsync("Navbar")


	@RenderBody();

	<partial name="_Footer" />


	<!-- JAVASCRIPTS -->
	<script src="~/plugins/jQuery/jquery.min.js"></script>
	<script src="~/plugins/bootstrap/js/popper.min.js"></script>
	<script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/plugins/bootstrap/js/bootstrap-slider.js"></script>
	<!-- tether js -->
	<script src="~/plugins/tether/js/tether.min.js"></script>
	<script src="~/plugins/raty/jquery.raty-fa.js"></script>
	<script src="~/plugins/slick-carousel/slick/slick.min.js"></script>
	<script src="~/plugins/jquery-nice-select/js/jquery.nice-select.min.js"></script>
	<script src="~/plugins/fancybox/jquery.fancybox.pack.js"></script>
	<script src="~/plugins/smoothscroll/SmoothScroll.min.js"></script>
	<!-- google map -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
	<script src="~/plugins/google-map/gmap.js"></script>
	<script src="~/js/script.js"></script>

	 @await RenderSectionAsync("Heads", required: false)

	 @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

AspNetMvcAds.Web.Mvc/Views/Shared/_LayoutBasic.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspnetMvcAds</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Heads", required: false)
</head>
<body>
    @RenderBody()
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>