AspNetMvcAds.Web.Mvc/Areas/Admin/Controllers/AdvertController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdvertController : Controller
    {
        // Admin / Advert
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/Controllers/CategoryController.cs
using AspNetMvcAds.Business;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;

        public CategoryController(ICategoryService categoryService, IProductService productService)
        {
            _categoryService = categoryService;
            _productService = productService;
        }

        // category/index/cid
        public IActionResult Index(int cid)
        {
            var list = _productService.GetAllAdvert(cid);
            ViewBag.SubCategories = _categoryService.GetAllSubCategories();
            return View(list);
        }

        public IActionResult AddListing()
        {
            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/Views/Shared/Components/HeroArea/Default.cshtml
@model HeroViewModel

<section class="hero-area bg-1 text-center overly">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- Header Contetnt -->
				<div class="content-block">
					<h1>Buy & Sell Near You </h1>
					<p>Join the millions who buy and sell from each other <br> everyday in local communities around the world</p>
					<div class="short-popular-category-list text-center">
						<h2>Popular Category</h2>
						<ul class="list-inline">
							@foreach(var category in Model.PopularCategories) {
								<li class="list-inline-item">
									<a asp-controller="Category" asp-action="Index" asp-route-cid="@category.Id">
										<i class="fa @category.Logo"></i> 
										@category.Name
									</a>
								</li>
							}
						</ul>
					</div>

				</div>
				<!-- Advance Search -->
				<div class="advance-search">
					<div class="container">
						<div class="row justify-content-center">
							<div class="col-lg-12 col-md-12 align-content-center">
								<form asp-controller="Advert" asp-action="Search">
									<div class="form-row">
										<div class="form-group col-md-4">
											<input type="search" class="form-control my-2 my-lg-1" id="search" name="q" placeholder="What are you looking for">
										</div>
										<div class="form-group col-md-3">
											<select class="w-100 form-control mt-lg-1 mt-md-2" name="categoryId" asp-items="@Model.MainCategoriesSelectList"></select>
										</div>
										<div class="form-group col-md-3">
											<input type="text" class="form-control my-2 my-lg-1" name="location" placeholder="Location">
										</div>
										<div class="form-group col-md-2 align-self-center">

											<button type="submit" class="btn btn-primary">Search Now</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- Container End -->
</section>