AspNetMvcAds.Web.Mvc/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.Areas.Admin.Controllers
{
     [Area("Admin")]
    public class HomeController : Controller
    {        
        //Admin / Home
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/Controllers/HomeController.cs
using AspNetMvcAds.Business;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IPageService pageService;

    public HomeController(ILogger<HomeController> logger, IPageService pageService)
    {
        _logger = logger;
        this.pageService = pageService;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> AboutUs()
    {
        var page = await pageService.GetPageById(1);
        if (page != null)
            return View(page);
        else
            return NotFound();
    }

    public IActionResult ContactUs()
    {
        return View();
    }

    public IActionResult UserProfile()
    {
        return View();
    }

    public IActionResult Package()
    {
        return View();
    }

    public IActionResult StoreSingle()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View();
    }
}

AspNetMvcAds.Web.Mvc/ViewComponents/CategoriesViewComponent.cs
using AspNetMvcAds.Business;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;

        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.MainCategories = categoryService.GetAllMainCategories();

            ViewBag.SubCategories = categoryService.GetAllSubCategories();

            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/ViewComponents/HeroAreaViewComponent.cs
using AspNetMvcAds.Business;
using AspNetMvcAds.Web.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AspNetMvcAds.Web.Mvc.ViewComponents
{
    public class HeroAreaViewComponent : ViewComponent
    {
        private readonly ICategoryService _service;

        public HeroAreaViewComponent(ICategoryService service)
        {
            _service = service;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var vm = new HeroViewModel()
            {
                MainCategoriesSelectList = _service.GetAllMainCategories().Select(e => new SelectListItem { Text = e.Name, Value = e.Id.ToString() }).ToList(),
                PopularCategories = _service.GetPopularCategories()
            };

            return View(vm);
        }
    }
}

AspNetMvcAds.Web.Mvc/ViewComponents/PopularDealsViewComponent.cs
using AspNetMvcAds.Business;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcAds.Web.Mvc.ViewComponents
{
    public class PopularDealsViewComponent : ViewComponent
    {
        private readonly IProductService _productService;

        public PopularDealsViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.AllTrendingAdds = _productService.GetAllTrendingsAdds();

            return View();
        }
    }
}

AspNetMvcAds.Web.Mvc/Views/Home/AboutUs.cshtml
@model Page

<!--================================
=            Page Title            =
=================================-->
<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2 text-center">
				<!-- Title text -->
				<h3>@Model.Title</h3>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

<section class="section">
	<div class="container">
		@Model.Content
	</div>
</section>

<section class="mb-5">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="heading text-center text-capitalize font-weight-bold py-5">
					<h2>our team</h2>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="card my-3 my-lg-0">
					<img class="card-img-top" src="~/images/team/team1.jpg" class="img-fluid w-100" alt="Card image cap">
					<div class="card-body bg-gray text-center">
						<h5 class="card-title">John Doe</h5>
						<p class="card-text">Founder / CEO</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="card my-3 my-lg-0">
					<img class="card-img-top" src="~/images/team/team2.jpg" class="img-fluid w-100" alt="Card image cap">
					<div class="card-body bg-gray text-center">
						<h5 class="card-title">John Doe</h5>
						<p class="card-text">Founder / CEO</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="card my-3 my-lg-0">
					<img class="card-img-top" src="~/images/team/team3.jpg" class="img-fluid w-100" alt="Card image cap">
					<div class="card-body bg-gray text-center">
						<h5 class="card-title">John Doe</h5>
						<p class="card-text">Founder / CEO</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="card my-3 my-lg-0">
					<img class="card-img-top" src="~/images/team/team4.jpg" class="img-fluid w-100" alt="Card image cap">
					<div class="card-body bg-gray text-center">
						<h5 class="card-title">John Doe</h5>
						<p class="card-text">Founder / CEO</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="section bg-gray">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-sm-6 my-lg-0 my-3">
				<div class="counter-content text-center bg-light py-4 rounded">
					<i class="fa fa-smile-o d-block"></i>
					<span class="counter my-2 d-block" data-count="2314">0</span>
					<h5>Happy Customers</h5>
					</script>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 my-lg-0 my-3">
				<div class="counter-content text-center bg-light py-4 rounded">
					<i class="fa fa-user-o d-block"></i>
					<span class="counter my-2 d-block" data-count="1013">0</span>
					<h5>Active Members</h5>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 my-lg-0 my-3">
				<div class="counter-content text-center bg-light py-4 rounded">
					<i class="fa fa-bookmark-o d-block"></i>
					<span class="counter my-2 d-block" data-count="2413">0</span>
					<h5>Verified Ads</h5>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 my-lg-0 my-3">
				<div class="counter-content text-center bg-light py-4 rounded">
					<i class="fa fa-smile-o d-block"></i>
					<span class="counter my-2 d-block" data-count="200">0</span>
					<h5>Happy Customers</h5>
				</div>
			</div>
		</div>
	</div>
</section>

AspNetMvcAds.Web.Mvc/Views/Home/ContactUs.cshtml
<!-- page title -->
<!--================================
=            Page Title            =
=================================-->
<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2 text-center">
				<!-- Title text -->
				<h3>Contact Us</h3>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>
<!-- page title -->
<!-- contact us start-->
<section class="section">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="contact-us-content p-4">
					<h5>Contact Us</h5>
					<h1 class="pt-3">Hello, what's on your mind?</h1>
					<p class="pt-3 pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elit dolor, blandit vel euismod ac, lentesque et dolor. Ut id tempus ipsum.</p>
				</div>
			</div>
			<div class="col-md-6">
				<form action="#">
					<fieldset class="p-4">
						<div class="form-group">
							<div class="row">
								<div class="col-lg-6 py-2">
									<input type="text" placeholder="Name *" class="form-control" required>
								</div>
								<div class="col-lg-6 pt-2">
									<input type="email" placeholder="Email *" class="form-control" required>
								</div>
							</div>
						</div>
						<select name="" id="" class="form-control w-100">
							<option value="1">Select Category</option>
							<option value="1">Laptop</option>
							<option value="1">iPhone</option>
							<option value="1">Monitor</option>
							<option value="1">I need</option>
						</select>
						<textarea name="message" id="" placeholder="Message *" class="border w-100 p-3 mt-3 mt-lg-4"></textarea>
						<div class="btn-grounp">
							<button type="submit" class="btn btn-primary mt-2 float-right">SUBMIT</button>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</section>
<!-- contact us end -->

AspNetMvcAds.Web.Mvc/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

@await Component.InvokeAsync("HeroArea")

@await Component.InvokeAsync("PopularDeals")

@await Component.InvokeAsync("Categories")

<partial name="_CallToAction" />

AspNetMvcAds.Web.Mvc/Views/Home/Package.cshtml
<section class="section bg-gray">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="heading text-center pb-5">
					<h2 class="font-weight-bold">Best Price Guaranteed</h2>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="package-content bg-light border text-center p-5 my-2 my-lg-0">
					<div class="package-content-heading border-bottom">
						<i class="fa fa-paper-plane"></i>
						<h2>Basic Package</h2>
						<h4 class="py-3"> <span>$10.00</span> Per Month</h4>
					</div>
					<ul>
						<li class="my-4"> <i class="fa fa-check"></i> Free Ad Posting</li>
						<li class="my-4"> <i class="fa fa-check"></i>15 Features Ad Availability</li>
						<li class="my-4"> <i class="fa fa-check"></i>For 15 Days</li>
						<li class="my-4"> <i class="fa fa-check"></i>100% Secure</li>
					</ul>
					<a href="#" class="btn btn-primary">Buy Now</a>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="package-content bg-light border text-center my-2 my-lg-0 p-5">
					<div class="package-content-heading border-bottom">
						<i class="fa fa-plane"></i>
						<h2>Standard Package</h2>
						<h4 class="py-3"> <span>$30.00</span> Per Month</h4>
					</div>
					<ul>
						<li class="my-4"> <i class="fa fa-check"></i> Free Ad Posting</li>
						<li class="my-4"> <i class="fa fa-check"></i>15 Features Ad Availability</li>
						<li class="my-4"> <i class="fa fa-check"></i>For 15 Days</li>
						<li class="my-4"> <i class="fa fa-check"></i>100% Secure</li>
					</ul>
					<a href="#" class="btn btn-primary">Buy Now</a>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 mx-sm-auto">
				<div class="package-content bg-light border text-center p-5 my-2 my-lg-0">
					<div class="package-content-heading border-bottom">
						<i class="fa fa-rocket"></i>
						<h2>Premium Package</h2>
						<h4 class="py-3"> <span>$50.00</span> Per Month</h4>
					</div>
					<ul>
						<li class="my-4"> <i class="fa fa-check"></i> Free Ad Posting</li>
						<li class="my-4"> <i class="fa fa-check"></i>15 Features Ad Availability</li>
						<li class="my-4"> <i class="fa fa-check"></i>For 15 Days</li>
						<li class="my-4"> <i class="fa fa-check"></i>100% Secure</li>
					</ul>
					<a href="#" class="btn btn-primary">Buy Now</a>
				</div>
			</div>
		</div>
	</div>
</section>

AspNetMvcAds.Web.Mvc/Views/Home/StoreSingle.cshtml
<!--===================================
=            Clients Section        =
====================================-->

<section class="client-slider-03">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<!-- Client Slider -->
			<div class="col-md-12">
				<!-- Client Slider -->
				<div class="category-slider">
					<!-- Client 01 -->
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Bed</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Hotels</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-car"></i>
							<h4>Cars</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-cutlery"></i>
							<h4>Restaurants</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-mobile"></i>
							<h4>Automobile</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-film"></i>
							<h4>Gym</h4>
						</a>
					</div>
					<!-- Client 01 -->
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-paragraph"></i>
							<h4>Park</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-play"></i>
							<h4>Play</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-building"></i>
							<h4>Real Estate</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-shopping-bag"></i>
							<h4>Shopping</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Electronics</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Health</h4>
						</a>
					</div>

				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

<section class="stores section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h2>More Stores</h2>
				</div>
				<!-- First Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">#</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Second Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">A</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Third Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">B</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Fourth Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">C</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

AspNetMvcAds.Web.Mvc/Views/Home/UserProfile.cshtml
<!--==================================
=            User Profile            =
===================================-->

<section class="user-profile section">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 col-lg-3 offset-lg-0">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user">
						<!-- User Image -->
						<div class="image d-flex justify-content-center">
							<img src="~/images/user/user-thumb.jpg" alt="" class="">
						</div>
						<!-- User Name -->
						<h5 class="text-center">Samanta Doe</h5>
					</div>
					<!-- Dashboard Links -->
					<div class="widget dashboard-links">
						<ul>
							<li><a class="my-1 d-inline-block" href="">Savings Dashboard</a></li>
							<li><a class="my-1 d-inline-block" href="">Saved Offer <span>(5)</span></a></li>
							<li><a class="my-1 d-inline-block" href="">Favourite Stores <span>(3)</span></a></li>
							<li><a class="my-1 d-inline-block" href="">Recommended</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-10 offset-md-1 col-lg-9 offset-lg-0">
				<!-- Edit Profile Welcome Text -->
				<div class="widget welcome-message">
					<h2>Edit profile</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
				</div>
				<!-- Edit Personal Info -->
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="widget personal-info">
							<h3 class="widget-header user">Edit Personal Information</h3>
							<form action="#">
								<!-- First Name -->
								<div class="form-group">
									<label for="first-name">First Name</label>
									<input type="text" class="form-control" id="first-name">
								</div>
								<!-- Last Name -->
								<div class="form-group">
									<label for="last-name">Last Name</label>
									<input type="text" class="form-control" id="last-name">
								</div>
								<!-- File chooser -->
								<div class="form-group choose-file d-inline-flex">
									<i class="fa fa-user text-center px-3"></i>
									<input type="file" class="form-control-file mt-2 pt-1" id="input-file">
								</div>
								<!-- Comunity Name -->
								<div class="form-group">
									<label for="comunity-name">Comunity Name</label>
									<input type="text" class="form-control" id="comunity-name">
								</div>
								<!-- Checkbox -->
								<div class="form-check">
									<label class="form-check-label" for="hide-profile">
										<input class="form-check-input mt-1" type="checkbox" value="" id="hide-profile">
										Hide Profile from Public/Comunity
									</label>
								</div>
								<!-- Zip Code -->
								<div class="form-group">
									<label for="zip-code">Zip Code</label>
									<input type="text" class="form-control" id="zip-code">
								</div>
								<!-- Submit button -->
								<button class="btn btn-transparent">Save My Changes</button>
							</form>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<!-- Change Password -->
						<div class="widget change-password">
							<h3 class="widget-header user">Edit Password</h3>
							<form action="#">
								<!-- Current Password -->
								<div class="form-group">
									<label for="current-password">Current Password</label>
									<input type="password" class="form-control" id="current-password">
								</div>
								<!-- New Password -->
								<div class="form-group">
									<label for="new-password">New Password</label>
									<input type="password" class="form-control" id="new-password">
								</div>
								<!-- Confirm New Password -->
								<div class="form-group">
									<label for="confirm-password">Confirm New Password</label>
									<input type="password" class="form-control" id="confirm-password">
								</div>
								<!-- Submit Button -->
								<button class="btn btn-transparent">Change Password</button>
							</form>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<!-- Change Email Address -->
						<div class="widget change-email mb-0">
							<h3 class="widget-header user">Edit Email Address</h3>
							<form action="#">
								<!-- Current Password -->
								<div class="form-group">
									<label for="current-email">Current Email</label>
									<input type="email" class="form-control" id="current-email">
								</div>
								<!-- New email -->
								<div class="form-group">
									<label for="new-email">New email</label>
									<input type="email" class="form-control" id="new-email">
								</div>
								<!-- Submit Button -->
								<button class="btn btn-transparent">Change email</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>